// Copyright 2026 Mark Alan Boykin
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// SPDX-License-Identifier: MPL-2.0

//! Immutable, generated voxel content for one admitted part palette.
//!
//! The core owns the body's role, envelope, attachment and palette selection.
//! This module turns those admitted inputs into presentation content, then
//! addresses the exact generated bytes.  It deliberately has no organism,
//! species, recipe, renderer or camera input: relatives share a part form
//! because they cite the same palette entry, rather than because a renderer
//! recognises an archetype.
//!
//! A [`ContentPack`] carries its generated bytes as well as the declared
//! grammar version and inputs.  Restore can therefore validate old content
//! rather than regenerating it through whatever the current build calls its
//! default palette.

use std::collections::{BTreeSet, VecDeque};

use mesocosm_core::{PartPalette, PartTemplate, Role, RoleShapes, VolumeRef, classify};
use serde::{Deserialize, Serialize};

use crate::{Volume, VolumeMap};

/// The first admitted voxel-part grammar.
pub const VOXEL_GRAMMAR_V1: u16 = 1;
/// One pack is the four role banks times their four palette slots.
pub const MAX_PACK_VOLUMES: usize = 16;
/// Safety bound for an independently serialised volume before allocation.
pub const MAX_VOLUME_VOXELS: usize = 64 * 64 * 64;
/// Neutral structural surface: bulk and stem tissue.
pub const MATERIAL_BODY: u8 = 240;
/// Neutral structural surface: limbs and tendrils.
pub const MATERIAL_LIMB: u8 = 241;
/// Neutral structural surface: leaves, plates and shells.
pub const MATERIAL_PLATE: u8 = 242;
/// Neutral structural surface: sensory bead or lens.
pub const MATERIAL_SENSOR: u8 = 243;
/// A dark structural seam, used on a limb's central joint plane.
pub const MATERIAL_JOINT: u8 = 244;
/// A pale structural edge, used sparingly on plate and sensor surfaces.
pub const MATERIAL_EDGE: u8 = 245;

/// Generated content and the palette whose templates cite it.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ContentPack {
    /// A version is part of the digest domain.  A later algorithm receives a
    /// new version rather than replacing bytes at an old address.
    pub version: u16,
    /// The exact role/shape vocabulary a world records in its snapshot.
    pub palette: PartPalette,
    /// A vector keeps the wire unambiguous and permits a useful duplicate
    /// refusal.  Resolution builds the ordered map the mesh layer consumes.
    pub entries: Vec<ContentEntry>,
}

/// One immutable part volume and every input that generated it.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ContentEntry {
    pub role: Role,
    /// Selector zero is the default template; one through three are extras.
    pub slot: u8,
    pub half_extent: [i32; 3],
    pub reference: VolumeRef,
    pub volume: Volume,
}

/// A pack that cannot truthfully resolve its palette.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ContentError {
    PaletteMismatch,
    InvalidExtent {
        half_extent: [i32; 3],
    },
    UnknownVersion {
        found: u16,
    },
    TooManyEntries {
        found: usize,
    },
    TooManyVoxels {
        found: usize,
    },
    VoxelCountMismatch {
        expected: usize,
        found: usize,
    },
    WrongRole {
        role: Role,
        actual: Role,
    },
    DuplicateEntry {
        role: Role,
        slot: u8,
    },
    MissingEntry {
        role: Role,
        slot: u8,
    },
    UnexpectedEntry {
        role: Role,
        slot: u8,
    },
    EnvelopeMismatch {
        role: Role,
        slot: u8,
        expected: [u32; 3],
        found: [u32; 3],
    },
    ReferenceMismatch {
        role: Role,
        slot: u8,
    },
    EmptyVolume {
        role: Role,
        slot: u8,
    },
    DisconnectedVolume {
        role: Role,
        slot: u8,
    },
}

impl ContentPack {
    /// Generates one immutable form for every admitted palette template.
    ///
    /// `base` supplies biological role and envelope facts.  The returned
    /// palette changes only `VolumeRef`s, so role classification, mass prices,
    /// attachment geometry and developmental selectors remain untouched.
    pub fn generate(base: PartPalette) -> Result<Self, ContentError> {
        let mut palette = base;
        let mut entries = Vec::new();

        for role in Role::ALL {
            let shapes = base.shapes(role);
            for (slot, template) in templates(shapes) {
                let volume = generate_volume(role, slot, template.half_extent)?;
                let reference =
                    content_ref(VOXEL_GRAMMAR_V1, role, slot, template.half_extent, &volume);
                entries.push(ContentEntry {
                    role,
                    slot,
                    half_extent: template.half_extent,
                    reference,
                    volume,
                });
                template_mut(&mut palette, role, slot).volume = reference;
            }
        }

        let pack = Self {
            version: VOXEL_GRAMMAR_V1,
            palette,
            entries,
        };
        pack.validate()?;
        Ok(pack)
    }

    /// Checks every declared input, envelope and content address, then returns
    /// the source a live projector needs.  No caller gets a partial map.
    pub fn resolve(&self) -> Result<VolumeMap, ContentError> {
        self.validate()?;
        let mut map = VolumeMap::new();
        for entry in &self.entries {
            map.insert(entry.reference, entry.volume.clone());
        }
        Ok(map)
    }

    /// Pairs persisted content with the palette in a restored world.
    pub fn resolve_for(&self, palette: PartPalette) -> Result<VolumeMap, ContentError> {
        if self.palette != palette {
            return Err(ContentError::PaletteMismatch);
        }
        self.resolve()
    }

    /// Verifies that this serialised bundle still means exactly what it says.
    pub fn validate(&self) -> Result<(), ContentError> {
        if self.version != VOXEL_GRAMMAR_V1 {
            return Err(ContentError::UnknownVersion {
                found: self.version,
            });
        }
        if self.entries.len() > MAX_PACK_VOLUMES {
            return Err(ContentError::TooManyEntries {
                found: self.entries.len(),
            });
        }

        let mut declared = BTreeSet::new();
        for entry in &self.entries {
            if !declared.insert((role_tag(entry.role), entry.slot)) {
                return Err(ContentError::DuplicateEntry {
                    role: entry.role,
                    slot: entry.slot,
                });
            }
            let voxels = volume_len(entry.volume.size)?;
            if voxels > MAX_VOLUME_VOXELS {
                return Err(ContentError::TooManyVoxels { found: voxels });
            }
            if entry.volume.voxel_count() != voxels {
                return Err(ContentError::VoxelCountMismatch {
                    expected: voxels,
                    found: entry.volume.voxel_count(),
                });
            }
            let expected = envelope(entry.half_extent)?;
            if entry.volume.size != expected {
                return Err(ContentError::EnvelopeMismatch {
                    role: entry.role,
                    slot: entry.slot,
                    expected,
                    found: entry.volume.size,
                });
            }
            let actual = classify(entry.half_extent);
            if actual != entry.role {
                return Err(ContentError::WrongRole {
                    role: entry.role,
                    actual,
                });
            }
            if entry.volume.is_empty() {
                return Err(ContentError::EmptyVolume {
                    role: entry.role,
                    slot: entry.slot,
                });
            }
            if !connected(&entry.volume) {
                return Err(ContentError::DisconnectedVolume {
                    role: entry.role,
                    slot: entry.slot,
                });
            }
            let digest = content_ref(
                self.version,
                entry.role,
                entry.slot,
                entry.half_extent,
                &entry.volume,
            );
            if digest != entry.reference {
                return Err(ContentError::ReferenceMismatch {
                    role: entry.role,
                    slot: entry.slot,
                });
            }
        }

        for role in Role::ALL {
            for (slot, template) in templates(self.palette.shapes(role)) {
                let Some(entry) = self
                    .entries
                    .iter()
                    .find(|entry| entry.role == role && entry.slot == slot)
                else {
                    return Err(ContentError::MissingEntry { role, slot });
                };
                if entry.half_extent != template.half_extent {
                    return Err(ContentError::EnvelopeMismatch {
                        role,
                        slot,
                        expected: envelope(template.half_extent)?,
                        found: entry.volume.size,
                    });
                }
                if entry.reference != template.volume {
                    return Err(ContentError::ReferenceMismatch { role, slot });
                }
            }
        }

        for entry in &self.entries {
            if !templates(self.palette.shapes(entry.role))
                .into_iter()
                .any(|(slot, _)| slot == entry.slot)
            {
                return Err(ContentError::UnexpectedEntry {
                    role: entry.role,
                    slot: entry.slot,
                });
            }
        }
        Ok(())
    }
}

fn templates(shapes: RoleShapes) -> Vec<(u8, PartTemplate)> {
    std::iter::once((0, shapes.default))
        .chain(
            shapes
                .extra
                .into_iter()
                .enumerate()
                .filter_map(|(index, template)| {
                    template.map(|template| (index as u8 + 1, template))
                }),
        )
        .collect()
}

fn template_mut(palette: &mut PartPalette, role: Role, slot: u8) -> &mut PartTemplate {
    let shapes = match role {
        Role::Mass => &mut palette.mass,
        Role::Limb => &mut palette.limb,
        Role::Plate => &mut palette.plate,
        Role::Sensor => &mut palette.sensor,
    };
    match slot {
        0 => &mut shapes.default,
        _ => shapes.extra[usize::from(slot - 1)]
            .as_mut()
            .expect("generation only visits admitted palette slots"),
    }
}

fn envelope(half_extent: [i32; 3]) -> Result<[u32; 3], ContentError> {
    if half_extent.iter().any(|half| *half < 0) {
        return Err(ContentError::InvalidExtent { half_extent });
    }
    let size = half_extent.map(|half| half.unsigned_abs().saturating_mul(2).max(1));
    let count = volume_len(size)?;
    if count > MAX_VOLUME_VOXELS {
        return Err(ContentError::TooManyVoxels { found: count });
    }
    Ok(size)
}

fn volume_len(size: [u32; 3]) -> Result<usize, ContentError> {
    let Some(count) = usize::try_from(size[0])
        .ok()
        .and_then(|x| x.checked_mul(size[1] as usize))
        .and_then(|x| x.checked_mul(size[2] as usize))
    else {
        return Err(ContentError::TooManyVoxels { found: usize::MAX });
    };
    Ok(count)
}

fn content_ref(
    version: u16,
    role: Role,
    slot: u8,
    half_extent: [i32; 3],
    volume: &Volume,
) -> VolumeRef {
    let mut hasher = blake3::Hasher::new();
    hasher.update(b"mesocosm.voxel-content");
    hasher.update(&version.to_le_bytes());
    hasher.update(&[role_tag(role), slot]);
    for extent in half_extent {
        hasher.update(&extent.to_le_bytes());
    }
    for size in volume.size {
        hasher.update(&size.to_le_bytes());
    }
    hasher.update(&volume.clone().into_voxels());
    VolumeRef(*hasher.finalize().as_bytes())
}

fn role_tag(role: Role) -> u8 {
    match role {
        Role::Mass => 0,
        Role::Limb => 1,
        Role::Plate => 2,
        Role::Sensor => 3,
    }
}

fn generate_volume(role: Role, slot: u8, half_extent: [i32; 3]) -> Result<Volume, ContentError> {
    let size = envelope(half_extent)?;
    let mut volume = Volume::empty(size);
    let axis = longest_axis(size);
    for z in 0..size[2] {
        for y in 0..size[1] {
            for x in 0..size[0] {
                let point = [x, y, z];
                if occupied(role, slot, size, axis, point) {
                    volume.set(x, y, z, surface_material(role, size, axis, point));
                }
            }
        }
    }
    Ok(volume)
}

fn surface_material(role: Role, size: [u32; 3], long: usize, point: [u32; 3]) -> u8 {
    match role {
        Role::Mass => MATERIAL_BODY,
        Role::Limb if point[long] == size[long].saturating_sub(1) / 2 => MATERIAL_JOINT,
        Role::Limb => MATERIAL_LIMB,
        Role::Plate if point[long] + 1 == size[long] => MATERIAL_EDGE,
        Role::Plate => MATERIAL_PLATE,
        Role::Sensor if point == [size[0] / 2, size[1] / 2, size[2] / 2] => MATERIAL_EDGE,
        Role::Sensor => MATERIAL_SENSOR,
    }
}

fn longest_axis(size: [u32; 3]) -> usize {
    (0..3).max_by_key(|axis| size[*axis]).unwrap()
}

fn occupied(role: Role, slot: u8, size: [u32; 3], long: usize, point: [u32; 3]) -> bool {
    // Values are doubled, so both even and one-cell envelopes remain
    // integer-exact without a display-space coordinate convention.
    let centred = [
        point[0] as i64 * 2 - (size[0] as i64 - 1),
        point[1] as i64 * 2 - (size[1] as i64 - 1),
        point[2] as i64 * 2 - (size[2] as i64 - 1),
    ];
    let radius = |axis: usize| (size[axis] as i64 - 1).max(1);
    // Even two-cell sections have centres at +/-1; preserve those cells.
    let radial = |axis: usize| centred[axis].abs() <= (radius(axis) / 2).max(1);
    let silhouette = match role {
        // A continuous tapered hull.  The end taper comes from the part's
        // own longest envelope axis, so a long axial segment is not a cube.
        Role::Mass => {
            let along = centred[long].abs();
            let taper = (radius(long) - along).max(0) * 2 + 1;
            (0..3)
                .filter(|axis| *axis != long)
                .all(|axis| centred[axis].abs() * radius(long).max(1) <= radius(axis) * taper)
        },
        // A rod with a narrow waist at each end.  It stays connected along
        // its long axis, giving limbs and stems a readable jointed rhythm.
        Role::Limb => {
            let along = centred[long].abs();
            let end = along * 3 >= radius(long) * 2;
            (0..3)
                .filter(|axis| *axis != long)
                .all(|axis| radial(axis) || (!end && centred[axis].abs() <= radius(axis)))
        },
        // A sheet or shell, pointed at the two broad axes.  Its thin axis is
        // selected from its actual envelope, so a pad and a flank shell need
        // no archetype-specific renderer path.
        Role::Plate => {
            let thin = (0..3).min_by_key(|axis| size[*axis]).unwrap();
            let broad: Vec<_> = (0..3).filter(|axis| *axis != thin).collect();
            let sum = centred[broad[0]].abs() * radius(broad[1])
                + centred[broad[1]].abs() * radius(broad[0]);
            let diamond = sum <= radius(broad[0]) * radius(broad[1]) + i64::from(slot);
            diamond && radial(thin)
        },
        // A compact lens.  Small functional eyes remain visibly distinct from
        // a decorative one-voxel sensor without borrowing a species name.
        Role::Sensor => (0..3).all(|axis| centred[axis].abs() <= radius(axis)),
    };
    silhouette || attachment_skeleton(size, point)
}

/// Keeps every central attachment port occupied. Development has already
/// declared a part's envelope and joins at its face centres; a surface grammar
/// may taper the silhouette but may not erase those actual joints.
fn attachment_skeleton(size: [u32; 3], point: [u32; 3]) -> bool {
    let centred = [
        point[0] as i64 * 2 - (size[0] as i64 - 1),
        point[1] as i64 * 2 - (size[1] as i64 - 1),
        point[2] as i64 * 2 - (size[2] as i64 - 1),
    ];
    let central = |axis: usize| centred[axis].abs() <= 1;
    (0..3).any(|axis| (0..3).filter(|other| *other != axis).all(central))
}

fn connected(volume: &Volume) -> bool {
    let Some(start) = (0..volume.size[2]).find_map(|z| {
        (0..volume.size[1]).find_map(|y| {
            (0..volume.size[0]).find_map(|x| (volume.get(x, y, z) != 0).then_some([x, y, z]))
        })
    }) else {
        return false;
    };
    let mut seen = BTreeSet::from([start]);
    let mut queue = VecDeque::from([start]);
    while let Some(point) = queue.pop_front() {
        for axis in 0..3 {
            for step in [-1i64, 1] {
                let mut next = point.map(i64::from);
                next[axis] += step;
                if next.iter().any(|coordinate| *coordinate < 0)
                    || next[0] >= i64::from(volume.size[0])
                    || next[1] >= i64::from(volume.size[1])
                    || next[2] >= i64::from(volume.size[2])
                {
                    continue;
                }
                let next = next.map(|coordinate| coordinate as u32);
                if volume.get(next[0], next[1], next[2]) != 0 && seen.insert(next) {
                    queue.push_back(next);
                }
            }
        }
    }
    seen.len() == volume.solid_count()
}

#[cfg(test)]
#[path = "content_tests.rs"]
mod tests;
