// Copyright 2026 Mark Alan Boykin
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// SPDX-License-Identifier: MPL-2.0

use mesocosm_core::{Founding, Role};

use super::*;

#[test]
fn v1_sensor_fixture_keeps_its_published_content_address() {
    // Independently hashed canonical bytes: domain, LE version 1, Sensor/1,
    // zero half-extents, LE size [1,1,1], one MATERIAL_EDGE byte (245).
    let pack = ContentPack::generate(Founding::default().palette()).unwrap();
    let sensor = pack
        .entries
        .iter()
        .find(|entry| entry.role == Role::Sensor && entry.slot == 1)
        .unwrap();
    let hex: String = sensor
        .reference
        .0
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect();
    assert_eq!(
        hex,
        "3bb7ba0ce31f3fd4ab25be0651be408f1ad6ad99c5a774a60ea640003a46148d"
    );
}

#[test]
fn generation_preserves_the_biological_palette_and_resolves_every_shape() {
    let base = Founding::default().palette();
    let pack = ContentPack::generate(base).expect("the default palette is bounded");
    let source = pack.resolve().expect("generated bytes address themselves");

    for role in Role::ALL {
        for (slot, before) in templates(base.shapes(role)) {
            let after = templates(pack.palette.shapes(role))
                .into_iter()
                .find(|(found, _)| *found == slot)
                .map(|(_, template)| template)
                .unwrap();
            assert_eq!(before.half_extent, after.half_extent);
            assert_ne!(before.volume, after.volume);
            assert!(crate::VolumeSource::volume(&source, after.volume).is_some());
        }
    }
}

#[test]
fn bytes_round_trip_without_a_regeneration_dependency() {
    let pack = ContentPack::generate(Founding::default().palette()).unwrap();
    let bytes = postcard::to_allocvec(&pack).unwrap();
    let restored: ContentPack = postcard::from_bytes(&bytes).unwrap();
    assert_eq!(restored, pack);
    assert!(restored.resolve().is_ok());
}

#[test]
fn changed_voxels_under_an_old_address_are_refused() {
    let mut pack = ContentPack::generate(Founding::default().palette()).unwrap();
    pack.entries[0].volume.set(2, 2, 2, 7);
    assert!(matches!(
        pack.resolve(),
        Err(ContentError::ReferenceMismatch { .. })
    ));
}

#[test]
fn every_generated_part_is_connected_has_ports_and_plates_are_shaped() {
    let pack = ContentPack::generate(Founding::default().palette()).unwrap();
    assert!(pack.entries.iter().all(|entry| connected(&entry.volume)));
    for entry in &pack.entries {
        for axis in 0..3 {
            let mut lower = [
                entry.volume.size[0] / 2,
                entry.volume.size[1] / 2,
                entry.volume.size[2] / 2,
            ];
            let mut upper = lower;
            lower[axis] = 0;
            upper[axis] = entry.volume.size[axis] - 1;
            assert_ne!(entry.volume.get(lower[0], lower[1], lower[2]), 0);
            assert_ne!(entry.volume.get(upper[0], upper[1], upper[2]), 0);
        }
    }
    assert!(
        pack.entries
            .iter()
            .filter(|entry| entry.role == Role::Plate)
            .all(|entry| { entry.volume.solid_count() < volume_len(entry.volume.size).unwrap() })
    );
}

#[test]
fn malformed_persisted_voxel_lengths_are_refused_before_traversal() {
    #[derive(serde::Serialize)]
    struct Raw {
        size: [u32; 3],
        voxels: Vec<u8>,
    }
    let mut pack = ContentPack::generate(Founding::default().palette()).unwrap();
    let raw = Raw {
        size: pack.entries[0].volume.size,
        voxels: vec![1],
    };
    pack.entries[0].volume = postcard::from_bytes(&postcard::to_allocvec(&raw).unwrap()).unwrap();
    assert!(matches!(
        pack.resolve(),
        Err(ContentError::VoxelCountMismatch { .. })
    ));
}

#[test]
fn empty_and_disconnected_content_are_named_refusals() {
    let mut empty = ContentPack::generate(Founding::default().palette()).unwrap();
    empty.entries[0].volume = Volume::empty(empty.entries[0].volume.size);
    refresh_entry(&mut empty, 0);
    assert!(matches!(
        empty.validate(),
        Err(ContentError::EmptyVolume { .. })
    ));

    let mut split = ContentPack::generate(Founding::default().palette()).unwrap();
    let entry = &mut split.entries[0];
    let mut volume = Volume::empty(entry.volume.size);
    volume.set(0, 0, 0, MATERIAL_BODY);
    volume.set(
        volume.size[0] - 1,
        volume.size[1] - 1,
        volume.size[2] - 1,
        MATERIAL_BODY,
    );
    entry.volume = volume;
    refresh_entry(&mut split, 0);
    assert!(matches!(
        split.validate(),
        Err(ContentError::DisconnectedVolume { .. })
    ));
}

fn refresh_entry(pack: &mut ContentPack, index: usize) {
    let (role, slot, reference) = {
        let entry = &mut pack.entries[index];
        entry.reference = content_ref(
            pack.version,
            entry.role,
            entry.slot,
            entry.half_extent,
            &entry.volume,
        );
        (entry.role, entry.slot, entry.reference)
    };
    template_mut(&mut pack.palette, role, slot).volume = reference;
}
